<?php

use App\Models\Quote;
use Illuminate\Database\Seeder;

class QuoteTableSeeder extends Seeder
{
    public function run()
    {
        $quotesArray = [
            ['text' => "As long as there was coffee in the world, how bad could things be?", 'author' => "Cassandra Clare"],
            ['text' => "I'd rather take coffee than compliments just now.", 'author' => "Louisa May Alcott"],
            ['text' => "Coffee is a way of stealing time that should by rights belong to your older self.", 'author' => "Terry Pratchett"],
            ['text' => "Black as night, sweet as sin.", 'author' => "Neil Gaiman"],
            ['text' => "I don't really like coffee, she said, but I don't really like it when my head hits my desk when I fall asleep either.", 'author' => "Brian Andreas"],
            ['text' => "Adventure in life is good; consistency in coffee even better.", 'author' => "Justina Chen"],
            ['text' => "An empty coffee cup is full of hope. Now there’s something worth voting for.", 'author' => "Jarod Kintz"],
            ['text' => "Come on, don't you ever stop and smell the coffee?", 'author' => "Justina Chen"],
            ['text' => "Coffee first. Schemes later.", 'author' => "Leanna Renee Hieber"],
            ['text' => "Do you know how helpless you feel if you have a full cup of coffee in your hand and you start to sneeze?", 'author' => "Jean Kerr"],
            ['text' => "Coffee and chocolate—the inventor of mocha should be sainted.", 'author' => "Cherise Sinclair"],
            ['text' => "No matter what historians claimed, BC really stood for 'Before Coffee'.", 'author' => "Cherise Sinclair"],
            ['text' => "Go sip on gossip, and leave the coffee talk for me to chug. I’ll be in the kitchen, giggling like a schoolgirl if you need me.", 'author' => "Jarod Kintz"],
            ['text' => "I’m a romantic. I like cold coffee and orgasms that arrive fifteen minutes after I’ve put on my clothes and paid the lady.", 'author' => "Jarod Kintz"],
            ['text' => "It doesn't matter where you're from - or how you feel... There's always peace in a strong cup of coffee.", 'author' => "Gabriel Bá"],
            ['text' => "I like my coffee with cream and my literature with optimism.", 'author' => "Abigail Reynolds"],
            ['text' => "My couch is coffee-colored. I can thank Starbucks and clumsiness for that.", 'author' => "Jarod Kintz"],
            ['text' => "Who shall I shoot? You choose. Now, listen very carefully: where's your coffee? You've got coffee, haven't you? C'mon, everyone's got coffee! Spill the beans!", 'author' => "Terry Pratchett"],
            ['text' => "Coffee is the common man’s gold, and like gold, it brings to every person the feeling of luxury and nobility", 'author' => "Sheik-Abd-al-Kadir"],
            ['text' => "Black as the devil, hot as hell, pure as an angel, sweet as love.", 'author' => "Charles Maurice de Talleyrand-Périgord"],
            ['text' => "I believe humans get a lot done, not because we're smart, but because we have thumbs so we can make coffee.", 'author' => "Flash Rosenberg"],
            ['text' => "Actually, this seems to be the basic need of the human heart in nearly every great crisis — a good hot cup of coffee.", 'author' => "Alexander King"],
            ['text' => "I would rather suffer with coffee than be senseless.", 'author' => "Napoleon Bonaparte"],
            ['text' => "Without my morning coffee I’m just like a dried up piece of roast goat.", 'author' => "Johann Sebastian Bach"],
            ['text' => "That’s something that annoys the hell out of me—I mean if somebody says the coffee’s all ready and it isn’t.", 'author' => "J.D. Salinger"],
            ['text' => "Good communication is just as stimulating as black coffee, and just as hard to sleep after.", 'author' => "Anne Morrow Lindbergh"],
            ['text' => "I never laugh until I've had my coffee.", 'author' => "Clark Gable"],
            ['text' => "As soon as coffee is in your stomach, there is a general commotion. Ideas begin to move... similes arise, the paper is covered. Coffee is your ally and writing ceases to be a struggle.", 'author' => "Honore de Balzac"],
            ['text' => "The powers of a man’s mind are directly proportioned to the quantity of coffee he drinks.", 'author' => "Sir James Mackintosh"],
            ['text' => "Coffee is a language in itself.", 'author' => "Jackie Chan"],
            ['text' => "I gave up coffee. It's almost worse than giving up a lover.", 'author' => "Sandra Bullock"],
            ['text' => "I think if I were a woman I’d wear coffee as a perfume.", 'author' => "John Van Drute"],
            ['text' => "I have measured out my life with coffee spoons", 'author' => "T.S. Elliot"],
            ['text' => "Coffee comes in five descending stages: Coffee, Java, Jamoke, Joe, and Carbon Remover", 'author' => "Robert A. Heinlein"],
            ['text' => "The voodoo priest and all his powers were as nothing compared to espresso, cappuccino, and mocha, which are stronger than all the religions of the world combined, and perhaps stronger than the human soul itself.", 'author' => "Mark Helprin"],
            ['text' => "A mathematician is a device for turning coffee into theorems.", 'author' => "Alfréd Rényi"],
            ['text' => "Way too much coffee. But if it weren't for the coffee, I'd have no identifiable personality whatsoever.", 'author' => "David Letterman"],
            ['text' => "I judge a restaurant by the bread and by the coffee.", 'author' => "Burt Lancaster"],
            ['text' => "Once you wake up and smell the coffee, it’s hard to go back to sleep.", 'author' => "Fran Drescher"],
            ['text' => "Blacker than a moonless night. Hotter and more bitter than Hell itself… That is coffee.", 'author' => "Godot in Phoenix Wright: Ace Attorney"],
            ['text' => "Life’s too short to drink crappy coffee and cry over boys who don’t care.", 'author' => "Matty Healy"],
            ['text' => "The morning cup of coffee has an exhilaration about it which the cheering influence of the afternoon or evening cup of tea cannot be expected to reproduce.", 'author' => "Oliver Wendell Holmes Sr."],
            ['text' => "Even bad coffee is better than no coffee at all.", 'author' => "David Lynch"],
            ['text' => "There are three intolerable things in life - cold coffee, lukewarm champagne, and overexcited women.", 'author' => "Orson Welles"],
            ['text' => "A morning coffee is my favorite way of starting the day, settling the nerves so that they don't later fray.", 'author' => "Marcia Carrington"],
            ['text' => "Just coffee. Black—like my soul.", 'author' => "Cassandra Clare"],
            ['text' => "I don't know where my ideas come from. I will admit, however, that one key ingredient is caffeine. I get a couple cups of coffee into me and weird things just start to happen.", 'author' => "Gary Larson"],
            ['text' => "I decide to turn to my old faithful solution to all that is wrong in life. Coffee.", 'author' => "Lisa Renee Jones"],
            ['text' => "There were some problems only coffee and ice cream could fix.", 'author' => "Amal El-Mohtar"],
            ['text' => "Somehow, the Good Lord don't want to see no man start a cold morning with just black coffee.", 'author' => "Robert Newton Peck"],
            ['text' => "The early morning is too strong to drink straight, so I need to mix in a little coffee to be able to hold it down.", 'author' => "Jarod Kintz"],
            ['text' => "The relationship between a perfect cup of coffee and a writer is just like the couple who always standby and feel proud of being committed to each other.", 'author' => "Himmilicious"],
            ['text' => "Never say no to coffee", 'author' => "Cesar"],
            ['text' => "Good. Coffee is good for you. It's the caffeine in it. Caffeine, we are here. Caffeine puts a man on her horse and a woman in his grave.", 'author' => "Ernest Hemmingway"],
            ['text' => "Isn't the smell of coffee the best alarm clock?", 'author' => "S.A. Tawks"],
            ['text' => "An aroma more heavenly than a flight of angels trickled on the breeze. 'Coffee!' He breathed the word like a prayer.", 'author' => "Karen Kincy"],
            ['text' => "The problem is NOT the PROBLEM...The problem is I haven’t had enough COFFEE to deal with the PROBLEM.", 'author' => "Tanya Masse"],
            ['text' => "When your blood runs black as the blackest night and your heart sounds as the warriors’ march, only then may you say, “I’ve had enough coffee.", 'author' => "Death Wish Coffee Co"],
            ['text' => "Love is blind. Especially in the morning, because I can't see a damn thing before having coffee.", 'author' => "Aleksandra Ninkovic"],
            ['text' => "What doesn’t KILL me makes me stronger… Except for the extinction of COFFEE… that might kill me.", 'author' => "Tanya Masse"],
            ['text' => "I need COFFEE to help me change the things I can... and WINE to help me accept the things I can't!", 'author' => "Tanya Masse"],
            ['text' => "The rich scent of my favorite caffeinated beverage sends trickles of pleasure across my skin as I step inside. Is there anything better than coffee? Chocolate maybe and sex ranks very close I suppose.", 'author' => "A.R. Miller"],
            ['text' => "Taste of coffee varies with the person on the other end of table.", 'author' => "Anonymous"],
            ['text' => "Coffee is not about having something to drink in cool weather, it's about having something to drink when you are not sleeping", 'author' => "Bobby Darnell"],
            ['text' => "That’s what I do: I make coffee and occasionally succumb to suicidal nihilism. But you shouldn’t worry — poetry is still first. Cigarettes and alcohol follow", 'author' => "Anne Sexton"],
            ['text' => "If this is decaf, I'm going to pour it on your head.", 'author' => "Audrey Bell"],
            ['text' => "But one day you're going to wake up to the smell of a friend making burnt toast and warm coffee, and you're going to smile with relief knowing you made it. Knowing somebody found ways to love you.", 'author' => "Vanessa Hogg"],
            ['text' => "Where do you get inspiration for your books? I tell myself I can't have another cup of coffee till I thought of an idea.", 'author' => "Douglas Adams"],
            ['text' => "Drink your coffee, it clears out the brain in the morning", 'author' => "Sergei Lukyanenko"],
            ['text' => "Some of the world's most effective thoughts happen over a brew of morning's coffee", 'author' => "Prabhukrishna M"],
            ['text' => "Our culture runs on coffee and gasoline, the first often tasting like the second.", 'author' => "Edward Abbey"],
            ['text' => "Love is a skeleton wrapped in a bacon blanket. It’s sizzling and hot and tasty and I’d love to have some right now with a large cup of coffee.", 'author' => "Jarod Kintz"],
            ['text' => "I ordered a single espresso because I wanted a drink I could hook up with.", 'author' => "Randy Kagan"],
            ['text' => "I like my coffee like I like myself....making rustling noises inside a burlap bag", 'author' => "Josh Stern"],
            ['text' => "It's the fine balance of caffeine and alcohol that bookends my days", 'author' => "Tim Minchin"],
            ['text' => "Coffee smells like how I imagine heaven will be scented.", 'author' => "Jarod Kintz"],
            ['text' => "No! I'm not ready, this is still my first cup of coffee!", 'author' => "Anthony Liccione"],
            ['text' => "A silent yawn is a scream for coffee", 'author' => "T. Haque"],
            ['text' => "The coffee's done? I LOVE IT WHEN THE COFFEE'S DONE!", 'author' => "Craig Benzine"],
            ['text' => "Day offers two equally necessary sacraments - the benediction of morning and the absolution of dusk. In the morning coffee blesses and in the evening wine absolves.", 'author' => "Michael Foley"],
            ['text' => "Is there any time in your life when you do not feel the need for caffeine? Sure. Sometimes I'm asleep.", 'author' => "Seanan McGuire"],
            ['text' => "LIFE is like coffee -- The darker it gets, the more it energizes.", 'author' => "Ankita Singhal"],
            ['text' => "Sometimes, they just make coffee cups too small.", 'author' => "Michelle M. Pillow"],
            ['text' => "Coffee is a warm drink that fosters friendship and tastes great. What more is there to life?", 'author' => "Kevin Sinnott"],
            ['text' => "Getting shot was an experience that Elise ranked on the 'unpleasantness' scale right around 'trying to survive a week without coffee'.", 'author' => "S.M. Reine"],
            ['text' => "It rather goes without saying that Katherine drank her coffee black. Katherines do, generally. They like their coffee like they like their ex-boyfriends: bitter.", 'author' => "John Green"],
            ['text' => "Writing Cave means it's Coffee O'Clock...Who am I kidding? It's always Coffee O'Clock!", 'author' => "Tammy-Louise Wilkins"],
            ['text' => "When my coffee is gone, so is my motivation.", 'author' => "Jarod Kintz"],
            ['text' => "The joke was that President Bush only declared war when Starbucks was hit. You can mess with the U.N. all you want, but when you start interfering with the right to get caffeinated, someone has to pay.", 'author' => "Chris Kyle"],
            ['text' => "A smoke, a book, a cup of coffee. These are the little things that get us through this sometimes weary world and all the rainy days.", 'author' => "R.M. Engelhardt"],
            ['text' => "A guy's gotta live, you know, gotta make his way and find his meaning in life and love, and to do that he needs coffee, he needs coffee and coffee and coffee.", 'author' => "Libba Bray"],
            ['text' => "We've only been sitting here forty minutes. I'm never at the morning table less than an hour and a half. I do some of my finest plotting over breakfast coffee and raisin brioche.", 'author' => "Dean Koontz"],
            ['text' => "I'm not a purist. Coffee drinking minus cream and sugar is an acquired taste. I'm still not sure it isn't like telling chefs to dispense with spices in cooking.", 'author' => "Kevin Sinnott"],
            ['text' => "I need coffee to deal with this, and I’m not getting decaf.", 'author' => "Matthew Arnold Stern"],
            ['text' => "No one can understand the truth until he drinks of coffee's frothy goodness.", 'author' => "Sheik Abd-al-Kadir"],
            ['text' => "What goes best with a cup of coffee? Another cup.", 'author' => "Henry Rollins"],
            ['text' => "No coffee can be good in the mouth that does not first send a sweet offering of odor to the nostrils.", 'author' => "Henry Ward Beecher"],
            ['text' => "Coffee is the best thing to douse the sunrise with.", 'author' => "Terri Guillemets"],
            ['text' => "Sleep is a symptom of caffeine deprivation.", 'author' => "Anonymous"],
            ['text' => "Decaffeinated coffee is the devil's blend.", 'author' => "Anonymous"],
            ['text' => "Chocolate, men, coffee — some things are better rich.", 'author' => "Anonymous"],
            ['text' => "Decaf? No, it's dangerous to dilute my caffeine stream.", 'author' => "Anonymous"],
            ['text' => "Coffee is a beverage that puts one to sleep when not drank.", 'author' => "Alphonse Allais"],
            ['text' => "Coffee smells like freshly ground heaven.", 'author' => "Jessi Lane Adams"],
            ['text' => "Caffeine isn't a drug, it's a vitamin! ", 'author' => "Anonymous"],
            ['text' => "Déjà Brew: The feeling that you've had this coffee before.", 'author' => "Anonymous"],
            ['text' => "Forever: Time it takes to brew the first pot of coffee in the morning.", 'author' => "Anonymous"],
            ['text' => "There's nothing sweeter than a cup of bitter coffee.", 'author' => "Rian Aditia"],
            ['text' => "I orchestrate my mornings to the tune of coffee.", 'author' => "Terri Guillemets"],
            ['text' => "Coffee is a hug in a mug.", 'author' => "Anonymous"],
            ['text' => "I can’t stop drinking the coffee. I stop drinking the coffee, I stop doing the standing and the walking and the words-putting-into-sentence doing", 'author' => "Amy Sherman-Palladino and Daniel Palladino"],
            ['text' => "You know you've been playing too much Nethack when you refer to coffee as a potion of sleep resistance.", 'author' => "Sweeney Todd Lundgren"],
            ['text' => "I don't have a problem with caffeine. I have a problem without caffeine!", 'author' => "Anonymous"],
            ['text' => "C:\COFFEE.POT missing (A)bort (R)etry (F)all asleep? ", 'author' => "Anonymous"],
            ['text' => "If it ain't caffeinated, it ain't coffee!", 'author' => "Anonymous"],
            ['text' => "Coffee and tobacco are complete repose.", 'author' => "Turkish Proverb"],
            ['text' => "In Seattle you haven't had enough coffee until you can thread a sewing machine while it's running.", 'author' => "Jeff Bezos"],
            ['text' => "Ultimate office automation — networked coffee machines.", 'author' => "Anonymous"],
            ['text' => "Decaf is like masturbating with an oven mitt!", 'author' => "Robin Williams"],
            ['text' => "Hot coffee and cold winter mornings are two of the best soul mates who ever did find each other.", 'author' => "Terri Guillemets"],
            ['text' => "It's amazing how the world begins to change through the eyes of a cup of coffee! ", 'author' => "Donna A. Favors"],
            ['text' => "Coffee makes me invincible. But when the cup is empty, I return to mere mortal. ", 'author' => "Terri Guillemets"],
            ['text' => "Water is the most essential element of life, because without it you can’t make coffee. ", 'author' => "Anonymous"],
            ['text' => "I just realized I’m not a morning person — I’m a coffee person.", 'author' => "Anonymous"],
            ['text' => "Only Irish coffee provides in a single glass all four essential food groups: alcohol, caffeine, sugar, and fat.", 'author' => "Alex Levine"],
            ['text' => "Ah well, a morning with weak coffee is still beaucoup better than a morning with no coffee.", 'author' => "Terri Guillemets"]
        ];

        $imagesArray = [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '4.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg',
            '8.jpg',
            '9.jpg',
            '10.jpg',
            '11.jpg',
            '12.jpg',
            '13.jpg',
            '14.jpg',
            '15.jpg',
            '16.jpg',
            '17.jpg',
            '18.jpg',
            '19.jpg',
            '20.jpg'
        ];

        foreach ($quotesArray as $quote) {
            Quote::create([
                'text' => $quote['text'],
                'author' => $quote['author'],
                'background' => $imagesArray[mt_rand(0, count($imagesArray) - 1)]
            ]);
        }
    }
}
